[package]
name = "chlorustical"
version = "0.2.0"
authors = ["Roland Metivier <metivier.roland@chlorophyt.us>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.9"